name: Java CI with Maven # Имя

on: [push, pull_request] # после чего будет выполняться

jobs:
  build: # задача

    runs-on: ubuntu-latest # будет выполняться на ОС ubuntu

    steps:
    - uses: actions/checkout@v2 # корнирование репризитория  для получения исходного кода
    - name: Set up JDK 11
      uses: actions/setup-java@v2 # установка JDK 
      with:
        java-version: '11' # версия jdk 11
        distribution: 'adopt'
    - name: Build with Maven 
      run: mvn -B -e verify # команда для сборки проекта, в данном виде запускает сборку и автотесты
